/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class FooTest {
    @Test void someFooMethodReturnsTrue() {
        Foo classUnderTest = new Foo();
        assertTrue(classUnderTest.someFooMethod(), "someFooMethod should return 'true'");
    }
}
